<?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
  <nav class="bulkActionButtons">
    <div style="padding: 0.5rem 1rem;display:flex;" class="bulk-checkbox">
      <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
      <label for="<?=$this->idPrefix?>addFormCheckboxSelectAll">
        <?=$this->transEsc('select_page')?>
      </label>
    </div>
    <div style="display:flex;margin:auto;">
    <span style="padding: 0.5rem 1rem;"><?=$this->transEsc('Vybrané')?>:</span>
    <ul class="action-toolbar">
      <?php if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <li><button id="ribbon-email" class="toolbar-btn" type="submit" name="email" value="1" title="<?=$this->transEscAttr('bookbag_email_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><i class="ph-envelope-simple"></i></button></li>
        <li><a target="_blank" href="<?=$this->url('export')?>/<?=$this->layout()->userLang?><?=$this->results->getUrlQuery()?>"><button id="ribbon-export" class="toolbar-btn" type="button" name="export" value="1" title="<?=$this->transEscAttr('bookbag_export_selected')?>"><i class="ph-download-simple"></i></button></a></li>
        <li><button id="ribbon-print" class="toolbar-btn" type="submit" name="print" value="1" title="<?=$this->transEscAttr('bookbag_print_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><i class="ph-printer"></i></button></li>
        <li><a target="_blank" href="<?=$this->url('sam')?>/<?=$this->layout()->userLang?>/<?=$this->results->getUrlQuery()?>"><button id="ribbon-charts" class="toolbar-btn" type="button" name="chart" value="1" title="<?=$this->transEscAttr('Show Charts')?>"><i class="ph-chart-bar"></i></button></a></li>
        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <li><button id="ribbon-save" class="toolbar-btn" type="submit" name="saveCart" value="1" title="<?=$this->transEscAttr('bookbag_save_selected')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><i class="ph-heart-straight"></i></button></li>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($this->showCartControls) && $this->showCartControls): ?>
        <li><button id="<?=$this->idPrefix?>updateCart" type="submit" class="toolbar-btn btn-type-add" name="add" value="1"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Add to Book Bag')?></button></li>
      <?php endif; ?>
    </ul>
    </div>
  </nav>
<?php endif; ?>
