<?php if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<?php $i = $this->indexStart; ?>
<?php $listStart = $this->results->getStartRecord() + $i - $this->indexStart; ?>
<ol id="wrapper" class="record-list wrapper" start="<?=$listStart?>">
  <?php foreach ($this->results->getResults() as $current): ?>
    <?php $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
    <li id="result<?=$i++ ?>" class="col result<?=$current->supportsAjaxStatus()?' ajaxItem':''?>">
      <?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
        <?=$this->record($current)->getCheckbox('', 'search-cart-form', $recordNumber)?>
      <?php endif; ?>
      <div class="record-number">
        <?=$recordNumber ?>
      </div>
      <?=$this->record($current)->getSearchResult('list')?>
    </li>
  <?php endforeach; ?>
</ol>
