<?php $account = $this->auth()->getManager(); ?>
<div class="banner container navbar">
  <div class="navbar-header">
    
    <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="https://clb.ucl.cas.cz">VuFind</a>
    <span id="title_text" style="font-size: x-large;padding: 20px;display:none;">Česká literární bibliografie</span>
  </div>
  <?php if ($this->layout()->searchbox !== false): ?>
    <div class="search container navbar">
      <nav class="nav searchbox hidden-print">
        <?=$this->layout()->searchbox ?>
      </nav>
    </div>
  <?php else: ?>
	<?php if (!str_contains($_SERVER['REQUEST_URI'], 'Advanced')): ?>
		<span style="font-size: x-large;padding: 20px;display: inline-block;">Česká literární bibliografie</span>
	<?php endif; ?>
  <?php endif; ?>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
    <?php if (str_contains($_SERVER['REQUEST_URI'], 'Advanced')): ?>
	<p class="adv_search_links">
	<a style="opacity:0.3;pointer-events: none" href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?><i class="ph-pencil-bold"></i></a>
        <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?><i class="ph-magnifying-glass-bold"></i></a>
        <a style="font-weight:bold;" href="Home<?=$hiddenFilterParams?>"><?=$this->transEsc("Start a new Basic Search")?><i class="ph-x-bold"></i></a>
      </p>
    <?php endif; ?>	
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul role="navigation" class="nav navbar-nav navbar-right flip">
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
	  <?php endif; ?>
	    <li id="question">
                <a href="<?//=$this->url('myresearch-userlogin')?>" data-lightbox><i class="ph-question" aria-hidden="true"></i></a>
            </li>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="ph-user" aria-hidden="true"></a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="ph-user" aria-hidden="true"></i></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="ph-globe" aria-hidden="true"></i></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>
        </ul>
      </nav>
    </div> 
  <?php endif; ?>
</div>
<div class="dedic_min">
	<button id="ded_div" class="dedic_div hidden">
	<i class="ph-hand-palm" style="font-size:50px;margin:auto;"></i>
	<span class="text-vert">DEDIKACE</span>	
	</button>
</div>

