<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
    $resourceInfo = $this->driver->CLB_getResourceInfo();
    $RET = 0;
    if ($resourceInfo[0] == "Retrospective Bibliography (up to 1945)"){
	    $RET = 1;
    }
  ?>
  <?php if ($QRCode || $cover || $preview): ?>
    <?php if ($RET): ?>
	<div class="media-ret">
		<h3 property="name"><?php print(array_keys($this->driver->getAuthorDataFields('primary'))[0]);?></h3>
    <?php else: ?>	
	<div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
    <?php endif; ?>
      <?php /* Display thumbnail if appropriate: */ ?>
      <!--<div class="format_title" style="display:flex;">
	<?php $formats = $this->record($this->driver)->getFormatList(); print_r(strtoupper($formats));?>
      </div>-->
      <div class="cover-img">
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>
      </div>
      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <?php if (!($RET)): ?>
  <div class="media-body">

    <h3 property="name"><?=$this->escapeHtml(rtrim($this->driver->getTitle(),'/'))?></h3>
    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if(!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$summary?></p>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?> 
  </div>
  <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
	<?php if ($this->permission()->allowDisplay('feature.Favorites')): ?>
	<div style="margin:auto;margin-right:0px;">
          <a class="save-record toolbar-btn" style="text-decoration:none;height:100%;" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Save'))?>" rel="nofollow"><i class="ph-heart-straight"></i></a>
        <?php elseif ($block = $this->permission()->getAlternateContent('feature.Favorites')): ?>
          <?=$block?>
	<?php endif; ?>
	</div>
    <?php endif; ?>

</div>
    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <table class="table table-core">
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
