<?php $alt = $this->link ? trim($this->driver->tryMethod('getTitle') ?? '') : ''; ?>
<?php if ($this->link && !empty($alt)): ?><a href="<?=$this->escapeHtmlAttr($this->link)?>" class="record-cover-link"><?php endif; ?>
<?php /* Display thumbnail if appropriate: */ ?>
<?php if ($cover): ?>
<div class="format_title" style="display:flex;">
<?php foreach ($this->driver->getFormats() as $format): ?>
  <?php if ($translated = $this->transEsc($format)): ?>
    <span class="<?=$this->record($this->driver)->getFormatClass($format) ?>"><?=strtoupper($translated) ?></span>
  <?php endif; ?>
<?php endforeach; ?>	
</div>
  <img src="<?=$this->escapeHtmlAttr($cover); ?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="<?=$this->escapeHtmlAttr($alt); ?>" />
<?php elseif ($cover === false): ?>
  <img src="<?=$this->url('cover-unavailable')?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt="" />
<?php else: ?>
  <div class="ajaxcover">
    <div class="spinner"><?=$this->icon('spinner') ?> <?=$this->translate('loading_ellipsis')?></div>
    <div class="cover-container">
      <img <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>data-context="<?=$this->escapeHtmlAttr($this->context)?>" data-recordsource="<?=$this->escapeHtmlAttr($driver->getSourceIdentifier())?>" data-recordid="<?=$this->escapeHtmlAttr($driver->getUniqueID())?>" data-coversize="<?=$this->escapeHtmlAttr($size)?>" class="recordcover ajax" alt="<?=$this->escapeHtmlAttr($alt); ?>" />
    </div>
  </div>
<?php endif; ?>
<?php if ($this->link && !empty($alt)): ?></a><?php endif; ?>
