<?php
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }
?>
<?php if ($this->usertags()->getMode() !== 'disabled'): ?>
  <?php $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
    <a class="tag-record btn btn-link pull-right flip" style="text-decoration:none;" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'AddTag'))?>" data-lightbox>
      <i class="ph-plus-circle"></i>
    </a>
    <?=$this->context($this)->renderInContext('record/taglist', ['tagList' => $tagList, 'loggedin' => $loggedin]) ?>
<?php endif; ?>
